include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_function_declarations_over_variables: false


analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart
  errors:
    todo: warning
