name: mqtt_flutter_bloc
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  hydrated_bloc: ^7.0.0
  flutter_bloc: ^7.0.0

  # Utils
  equatable: ^2.0.3
  device_info: ^2.0.0
  geolocator: ^7.0.3
  file_picker: ^3.0.1
  meta: ^1.3.0
  intl: ^0.17.0
  sentry_flutter: ^5.1.0

  # MQTT
  mqtt_client: ^9.3.2

  # Storage
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  path_provider: ^2.0.1
  cloud_firestore: ^2.4.0
  firebase_core: ^1.4.0

  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  google_maps_flutter: ^2.0.3
  syncfusion_flutter_gauges: ^19.1.57

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mockito: ^5.0.5
  sqflite_common_ffi: ^2.0.0+1
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.1

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/
    - assets/lang/
    - assets/map_styles/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
